[package]
name = "securefolder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chacha20poly1305 = { version = "0.10.1", features = ["stream", "heapless"] }
color-eyre = "0.6"
rand = "^0.7"
bincode = "1.3.3"
walkdir = "2.3.2"
tokio = { version = "1.21.2", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
memmap2 = "0.5.7"
argparse = "0.2.2"
lz4_flex = { version = "0.9.3", default-features = false, features=["frame"] }
ed25519-dalek = { version = "1.0.1", features = ["serde"] }
flexbuffers = { version = "2.0.0" }
