[package]
name = "securefolder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chacha20poly1305 = { version = "0.9.0", features = ["stream"] }
anyhow = "1.0"
rand = "0.8"
bincode = "1.3.3"
walkdir = "2.3.2"
tokio = { version = "1.21.2", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
argparse = "0.2.2"
lz4 = "1.24.0"
blake3 = "1.3.1"